/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calcula.h"

int *
adicao_1_svc(operandos *argp, struct svc_req *rqstp)
{
	static int  result;

	result = argp -> x + argp -> y;

	return &result;
}

int *
subtracao_1_svc(operandos *argp, struct svc_req *rqstp)
{
	static int  result;

	result = argp -> x - argp -> y;

	return &result;
}

int *
multiplicacao_1_svc(operandos *argp, struct svc_req *rqstp)
{
	static int  result;

	result = argp -> x * argp -> y;

	return &result;
}

int *
divisao_1_svc(operandos *argp, struct svc_req *rqstp)
{
	static int  result;

	result = argp -> x / argp -> y;

	return &result;
}
