/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALCULA_H_RPCGEN
#define _CALCULA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct operandos {
	int x;
	int y;
};
typedef struct operandos operandos;

#define CALCULA_PROG 55555
#define CALCULA_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define adicao 1
extern  int * adicao_1(operandos *, CLIENT *);
extern  int * adicao_1_svc(operandos *, struct svc_req *);
#define subtracao 2
extern  int * subtracao_1(operandos *, CLIENT *);
extern  int * subtracao_1_svc(operandos *, struct svc_req *);
#define multiplicacao 3
extern  int * multiplicacao_1(operandos *, CLIENT *);
extern  int * multiplicacao_1_svc(operandos *, struct svc_req *);
#define divisao 4
extern  int * divisao_1(operandos *, CLIENT *);
extern  int * divisao_1_svc(operandos *, struct svc_req *);
extern int calcula_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define adicao 1
extern  int * adicao_1();
extern  int * adicao_1_svc();
#define subtracao 2
extern  int * subtracao_1();
extern  int * subtracao_1_svc();
#define multiplicacao 3
extern  int * multiplicacao_1();
extern  int * multiplicacao_1_svc();
#define divisao 4
extern  int * divisao_1();
extern  int * divisao_1_svc();
extern int calcula_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_operandos (XDR *, operandos*);

#else /* K&R C */
extern bool_t xdr_operandos ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALCULA_H_RPCGEN */
