/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calcula.h"


void
calcula_prog_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	operandos  adicao_1_arg;
	int  *result_2;
	operandos  subtracao_1_arg;
	int  *result_3;
	operandos  multiplicacao_1_arg;
	int  *result_4;
	operandos  divisao_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, CALCULA_PROG, CALCULA_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = adicao_1(&adicao_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = subtracao_1(&subtracao_1_arg, clnt);
	if (result_2 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = multiplicacao_1(&multiplicacao_1_arg, clnt);
	if (result_3 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_4 = divisao_1(&divisao_1_arg, clnt);
	if (result_4 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	CLIENT *clnt;
	operandos ops;
	int *result;

	// Conectar ao servidor RPC
    clnt = clnt_create(argv[1], CALCULA_PROG, CALCULA_VERS, "udp");

    // Obter operandos a partir dos argumentos de linha de comando
    ops.x = atoi(argv[2]);
    ops.y = atoi(argv[3]);

	result = adicao_1(&ops,clnt);
	printf("%d + %d = %d\n", ops.x, ops.y, *result);

	result = subtracao_1(&ops,clnt);
	printf("%d - %d = %d\n", ops.x, ops.y, *result);

	result = multiplicacao_1(&ops,clnt);
	printf("%d * %d = %d\n", ops.x, ops.y, *result);

	result = divisao_1(&ops,clnt);
	printf("%d / %d = %d\n", ops.x, ops.y, *result);
	

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	calcula_prog_1 (host);
    clnt_destroy(clnt);

exit (0);
}
