/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SOMAVET_H_RPCGEN
#define _SOMAVET_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct vetor {
	int tamanho;
	struct {
		u_int numeros_len;
		int *numeros_val;
	} numeros;
};
typedef struct vetor vetor;

#define SOMAVET_PROG 66666666
#define SOMAVET_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define SOMA_VETOR 1
extern  int * soma_vetor_1(vetor *, CLIENT *);
extern  int * soma_vetor_1_svc(vetor *, struct svc_req *);
extern int somavet_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SOMA_VETOR 1
extern  int * soma_vetor_1();
extern  int * soma_vetor_1_svc();
extern int somavet_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_vetor (XDR *, vetor*);

#else /* K&R C */
extern bool_t xdr_vetor ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SOMAVET_H_RPCGEN */
