/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "somavet.h"

bool_t
xdr_vetor (XDR *xdrs, vetor *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->tamanho))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->numeros.numeros_val, (u_int *) &objp->numeros.numeros_len, ~0,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	return TRUE;
}
