/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "somavet.h"
#include <stdio.h>

int *soma_vetor_1_svc(vetor *vet, struct svc_req *rqstp) {
    static int soma;
    soma = 0;
    printf("Recebido vetor de tamanho %d\n", vet->numeros.numeros_len);

    // Percorre o vetor e soma os elementos
    for (int i = 0; i < vet->numeros.numeros_len; i++) {
        soma += vet->numeros.numeros_val[i];  // Usar numeros_val para acessar os elementos
    }

    printf("Soma dos elementos: %d\n", soma);
    return &soma;
}