/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "minMax.h"


void
minmax_prog_1(char *host)
{
	CLIENT *clnt;
	MinMax  *result_1;
	IntArray  find_min_max_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, MINMAX_PROG, MINMAX_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = find_min_max_1(&find_min_max_1_arg, clnt);
	if (result_1 == (MinMax *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int main(int argc, char *argv[]) {
    CLIENT *clnt;
    IntArray arr;
    MinMax *result;

    if (argc != 2) {
        fprintf(stderr, "Uso: %s <hostname>\n", argv[0]);
        exit(1);
    }

    // Criando o cliente RPC
    clnt = clnt_create(argv[1], MINMAX_PROG, MINMAX_VERS, "tcp");
    if (clnt == NULL) {
        clnt_pcreateerror(argv[1]);
        exit(1);
    }

    // Inicializando o vetor com valores aleatórios
    for (int i = 0; i < 100; i++) {
        arr.values[i] = rand() % 1000;
    }

    // Chamada ao procedimento remoto find_min_max
    result = find_min_max_1(&arr, clnt);
    if (result == NULL) {
        clnt_perror(clnt, argv[1]);
        exit(1);
    }

    // Imprimindo o resultado
    printf("Menor valor: %d, Maior valor: %d\n", result->min, result->max);

    // Destruindo o cliente
    clnt_destroy(clnt);
    return 0;
}
