/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "minMax.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

MinMax *
find_min_max_1(IntArray *argp, CLIENT *clnt)
{
	static MinMax clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, find_min_max,
		(xdrproc_t) xdr_IntArray, (caddr_t) argp,
		(xdrproc_t) xdr_MinMax, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
