/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _MINMAX_H_RPCGEN
#define _MINMAX_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct IntArray {
	int values[100];
};
typedef struct IntArray IntArray;

struct MinMax {
	int min;
	int max;
};
typedef struct MinMax MinMax;

#define MINMAX_PROG 55555
#define MINMAX_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define find_min_max 1
extern  MinMax * find_min_max_1(IntArray *, CLIENT *);
extern  MinMax * find_min_max_1_svc(IntArray *, struct svc_req *);
extern int minmax_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define find_min_max 1
extern  MinMax * find_min_max_1();
extern  MinMax * find_min_max_1_svc();
extern int minmax_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_IntArray (XDR *, IntArray*);
extern  bool_t xdr_MinMax (XDR *, MinMax*);

#else /* K&R C */
extern bool_t xdr_IntArray ();
extern bool_t xdr_MinMax ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_MINMAX_H_RPCGEN */
