/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CONTADOR_H_RPCGEN
#define _CONTADOR_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct Palavra {
	char *texto;
};
typedef struct Palavra Palavra;

struct Resposta {
	char *resultado;
};
typedef struct Resposta Resposta;

#define CONTADOR_PROG 55555555
#define CONTADOR_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define contabilizar_palavra 1
extern  Resposta * contabilizar_palavra_1(Palavra *, CLIENT *);
extern  Resposta * contabilizar_palavra_1_svc(Palavra *, struct svc_req *);
extern int contador_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define contabilizar_palavra 1
extern  Resposta * contabilizar_palavra_1();
extern  Resposta * contabilizar_palavra_1_svc();
extern int contador_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Palavra (XDR *, Palavra*);
extern  bool_t xdr_Resposta (XDR *, Resposta*);

#else /* K&R C */
extern bool_t xdr_Palavra ();
extern bool_t xdr_Resposta ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CONTADOR_H_RPCGEN */
