/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "contador.h"

void
contador_prog_1(char *host)
{
	CLIENT *clnt;
	Resposta  *result_1;
	Palavra  contabilizar_palavra_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, CONTADOR_PROG, CONTADOR_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = contabilizar_palavra_1(&contabilizar_palavra_1_arg, clnt);
	if (result_1 == (Resposta *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


void modo_inclusao(char *host, char *arquivo_entrada) {
    FILE *file = fopen(arquivo_entrada, "r");
    if (file == NULL) {
        perror("Erro ao abrir arquivo");
        exit(1);
    }

    CLIENT *clnt = clnt_create(host, CONTADOR_PROG, CONTADOR_VERS, "udp");
    if (clnt == NULL) {
        clnt_pcreateerror(host);
        fclose(file);
        exit(1);
    }

    Palavra palavra;
    Resposta *resposta;
    char linha[128];

    // Inicializando a estrutura para evitar acesso a lixo de memória
    memset(&palavra, 0, sizeof(palavra));

    while (fgets(linha, sizeof(linha), file)) {
        linha[strcspn(linha, "\n")] = 0; // Remove o '\n' do final da linha
        strncpy(palavra.texto, linha, sizeof(palavra.texto) - 1);
        palavra.texto[sizeof(palavra.texto) - 1] = '\0'; // Garante terminação nula

        // Chama o procedimento remoto
        resposta = contabilizar_palavra_1(&palavra, clnt);
        if (resposta == NULL) {
            clnt_perror(clnt, "Erro na chamada RPC");
            continue;
        }

        // Verifica se a resposta contém algum dado
        if (resposta->resultado[0] != '\0') {
            printf("%s\n", resposta->resultado);
        } else {
            printf("Erro: resposta vazia do servidor.\n");
        }
    }

    fclose(file);
    clnt_destroy(clnt);
}

void modo_consulta(char *host) {
    CLIENT *clnt = clnt_create(host, CONTADOR_PROG, CONTADOR_VERS, "udp");
    if (clnt == NULL) {
        clnt_pcreateerror(host);
        exit(1);
    }

    Palavra palavra;
    Resposta *resposta;

    // Inicializando a estrutura para evitar acesso a lixo de memória
    memset(&palavra, 0, sizeof(palavra));
    strcpy(palavra.texto, "IMPRIMIR");

    resposta = contabilizar_palavra_1(&palavra, clnt);
    if (resposta == NULL) {
        clnt_perror(clnt, "Erro na chamada RPC");
        clnt_destroy(clnt);
        exit(1);
    }

    if (resposta->resultado[0] != '\0') {
        printf("Dicionário:\n%s", resposta->resultado);
    } else {
        printf("Erro: resposta vazia do servidor.\n");
    }

    clnt_destroy(clnt);
}

int main(int argc, char *argv[]) {
    if (argc < 3) {
        fprintf(stderr, "Uso: %s <hostname> <modo> [arquivo]\nModos:\n  inclusao <arquivo>\n  consulta\n", argv[0]);
        exit(1);
    }

    char *host = argv[1];
    char *modo = argv[2];

    if (strcmp(modo, "inclusao") == 0 && argc == 4) {
        modo_inclusao(host, argv[3]);
    } else if (strcmp(modo, "consulta") == 0) {
        modo_consulta(host);
    } else {
        fprintf(stderr, "Modo inválido.\n");
        exit(1);
    }

    return 0;
}