/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "contador.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

Resposta *
contabilizar_palavra_1(Palavra *argp, CLIENT *clnt)
{
	static Resposta clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, contabilizar_palavra,
		(xdrproc_t) xdr_Palavra, (caddr_t) argp,
		(xdrproc_t) xdr_Resposta, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
